version: '3.8'
services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/myapp_db
    depends_on:
      - db
      - mongo
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
volumes:
  postgres_data:
